name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.md'
      - 'requirements*.txt'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.md'
      - 'requirements*.txt'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Python linting
      run: |
        flake8 .

    - name: Check Python formatting
      run: |
        black --check .

    - name: Check Markdown formatting
      run: |
        mdformat --check **/*.md

    - name: Build MkDocs
      run: |
        mkdocs build --strict

    - name: Run tests
      run: |
        python -m unittest discover -v

    - name: Run coverage
      run: |
        coverage run -m unittest discover
        coverage report